version: '3'
services:
    latexlab:
        restart: always
        image: denmor/latex-jupyterlab:latest
        container_name: latexlab
        environment:
            LOCAL_UID: "1000"
            LOCAL_GID: "1000"
            JUPYTER_ENABLE_LAB: "yes"
        ports:
            - 8888:8888
        volumes:
             - /var/lib/latexlab/data:/host/work
             - /var/lib/latexlab/texmf:/host/texmf
             - /var/lib/latexlab/config:/etc/jupyter
