version: '3'
services:
    latexlab:
        restart: always
        image: denmor/latex-jupyterlab:latest
        container_name: latexlab
        environment:
            LOCAL_UID: "1000"
            LOCAL_GID: "1000"
            JUPYTER_ENABLE_LAB: "yes"
        ports:
            - 9999:8888
        volumes:
             - /Users/denismorel/Documents/Development/tests/latexlab/data:/home/jovyan/work
             - /Users/denismorel/Documents/Development/tests/latexlab/texmf:/home/jovyan/texmf
             - /Users/denismorel/Documents/Development/tests/latexlab/config:/etc/jupyter
